Repository kncaputo/underrated, pull requests merged in 2020-12, with the labels that each got.

#1 Feature/initial display
  .eslintcache
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.test.js
  src/MovieGrid/MovieGrid.css
  src/MovieGrid/MovieGrid.js
  src/MovieGrid/MovieGrid.test.js
  src/MovieTrailers/MovieTrailers.css
  src/MovieTrailers/MovieTrailers.js
  src/MovieTrailers/MovieTrailers.test.js
  src/Poster/Poster.css
  src/Poster/Poster.js
  src/Poster/Poster.test.js
  src/SearchBar/SearchBar.css
  src/SearchBar/SearchBar.js
  src/SearchBar/SearchBar.test.js
  src/apiCalls.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: components, feature, router, styles

#2 Feature/movie details
  .eslintcache
  package-lock.json
  package.json
  src/App/App.css
  src/ListItem/ListItem.css
  src/ListItem/ListItem.js
  src/ListItem/ListItem.test.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/MovieTrailers/MovieTrailers.css
  src/MovieTrailers/MovieTrailers.js
Labels: components, enhancement, feature, styles

#10 Feature/login
  .eslintcache
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/Login/Login.css
  src/Login/Login.js
  src/Login/Login.test.js
  src/MovieDetails/MovieDetails.css
  src/Poster/Poster.css
  src/apiCalls.js
Labels: feature

#13 Feature/user functionality
  .eslintcache
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/MovieTrailers/MovieTrailers.js
  src/StarRating/StarRating.js
  src/apiCalls.js
Labels: components, enhancement, feature
