Repository kncaputo/underrated, pull requests merged in 2021-01, with the labels that each got.

#18 Refactor/code cleanup
  .eslintcache
  src/App/App.css
  src/App/App.js
  src/ListItem/ListItem.css
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/MovieTrailers/MovieTrailers.css
  src/MovieTrailers/MovieTrailers.js
  src/StarRating/StarRating.js
  src/apiCalls.js
Labels: fix, router, styles

#19 Feature/sort and filter
  .eslintcache
  src/App/App.css
  src/App/App.js
  src/Banner/Banner.css
  src/Banner/Banner.js
  src/ListItem/ListItem.js
  src/MovieDetails/MovieDetails.css
  src/Poster/Poster.js
  src/Search/Search.css
  src/Search/Search.js
  src/SearchBar/SearchBar.css
  src/SearchBar/SearchBar.js
  src/SearchBar/SearchBar.test.js
Labels: components, enhancement, feature

#27 Cleanup/dropdown button and styles
  .eslintcache
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/App/App.scss
  src/Banner/Banner.js
  src/Banner/Banner.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/ListItem/ListItem.js
  src/ListItem/ListItem.scss
  src/Login/Login.css
  src/Login/Login.js
  src/Login/Login.scss
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.scss
  src/MovieGrid/MovieGrid.js
  src/MovieGrid/MovieGrid.scss
  src/MovieTrailers/MovieTrailers.js
  src/MovieTrailers/MovieTrailers.scss
  src/Poster/Poster.js
  src/Poster/Poster.scss
  src/Search/Search.css
  src/Search/Search.js
  src/Search/Search.scss
  src/Watchlist/Watchlist.js
  src/Watchlist/Watchlist.scss
  src/index.js
  src/index.scss
  src/scss/_mixins.scss
  src/scss/_variables.scss
Labels: components, enhancement, fix, styles
